NICKNAME = "gigibot"
REALNAME = "gigibot"

SERVER = ("test.irc.ru", 6667)
CHANNELS = ["#chan1", "#chan2"]

TWITTER_CONSUMER_KEY = ""
TWITTER_CONSUMER_SECRET = ""
TWITTER_ACCESS_KEY = ""
TWITTER_ACCESS_SECRET = ""

